# Generated by Django 3.0 on 2022-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0002_user'),
    ]

    operations = [
    
    ]
